### ISSUE TITLE
Underscore in Prestashop plugin might cause installation issues

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-prestashop#8]
We have become aware that the underscore ( _ ) in the plugin's name is causing issues for merchants when installing the plugin (especially on web servers that are based on NGINX.

Please update the code to remove all instances of underscore ( _ ) and other special characters.

Please see screenshot below which reveals there are almost 21 instances of underscore usage in the plugin's name (oxipay_prestashop); please change to (oxipayprestashop).

![image](https://cloud.githubusercontent.com/assets/22509613/25265474/7b8b246e-26ac-11e7-83bd-0e305e3fd8a1.png)

**Comment by ramanjeetaulakh-qait** [comment]
[QAIT] Experiencing error at time of uploading oxipay plugin to Prestashop

Tried on below Tech-Stacks:
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)

Ubuntu 14.04
PHP version: (5.5.9)
Apache: (2.4.7)
mysql: (14.14) 

Prestashop (1.7.1.1)
Oxipay_Prestashop (0.1.0)

Screen cast:http://screencast-o-matic.com/watch/cbfT6KXI25

**Comment by blueninja2** [comment]
We currently have a fix for this and we'll hopefully have a new release of the plugin out tomorrow morning (Adelaide Time) that will resolve this.

**Comment by hellotaotao** [comment]
fixed in commit 676139e (release v1.0.10)
